# Generated by Django 5.0.6 on 2024-05-17 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 14, 14, 7, 32137), verbose_name='date published'),
        ),
    ]
